/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificacoesRouteImport } from './routes/certificacoes'
import { Route as ProjetosSlugRouteImport } from './routes/projetos/$slug'
import { Route as ProjetosAnaliseVendasXsalesRouteImport } from './routes/projetos/analise-vendas-xsales'
import { Route as ProjetosDashboardJuridicoRouteImport } from './routes/projetos/dashboard-juridico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificacoesRoute = CertificacoesRouteImport.update({
  id: '/certificacoes',
  path: '/certificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosAnaliseVendasXsalesRoute =
  ProjetosAnaliseVendasXsalesRouteImport.update({
    id: '/projetos/analise-vendas-xsales',
    path: '/projetos/analise-vendas-xsales',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjetosDashboardJuridicoRoute =
  ProjetosDashboardJuridicoRouteImport.update({
    id: '/projetos/dashboard-juridico',
    path: '/projetos/dashboard-juridico',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificacoes': typeof CertificacoesRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/analise-vendas-xsales': typeof ProjetosAnaliseVendasXsalesRoute
  '/projetos/dashboard-juridico': typeof ProjetosDashboardJuridicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificacoes': typeof CertificacoesRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/analise-vendas-xsales': typeof ProjetosAnaliseVendasXsalesRoute
  '/projetos/dashboard-juridico': typeof ProjetosDashboardJuridicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificacoes': typeof CertificacoesRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/analise-vendas-xsales': typeof ProjetosAnaliseVendasXsalesRoute
  '/projetos/dashboard-juridico': typeof ProjetosDashboardJuridicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificacoes'
    | '/projetos/$slug'
    | '/projetos/analise-vendas-xsales'
    | '/projetos/dashboard-juridico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificacoes'
    | '/projetos/$slug'
    | '/projetos/analise-vendas-xsales'
    | '/projetos/dashboard-juridico'
  id:
    | '__root__'
    | '/'
    | '/certificacoes'
    | '/projetos/$slug'
    | '/projetos/analise-vendas-xsales'
    | '/projetos/dashboard-juridico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificacoesRoute: typeof CertificacoesRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosAnaliseVendasXsalesRoute: typeof ProjetosAnaliseVendasXsalesRoute
  ProjetosDashboardJuridicoRoute: typeof ProjetosDashboardJuridicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificacoes': {
      id: '/certificacoes'
      path: '/certificacoes'
      fullPath: '/certificacoes'
      preLoaderRoute: typeof CertificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/analise-vendas-xsales': {
      id: '/projetos/analise-vendas-xsales'
      path: '/projetos/analise-vendas-xsales'
      fullPath: '/projetos/analise-vendas-xsales'
      preLoaderRoute: typeof ProjetosAnaliseVendasXsalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/dashboard-juridico': {
      id: '/projetos/dashboard-juridico'
      path: '/projetos/dashboard-juridico'
      fullPath: '/projetos/dashboard-juridico'
      preLoaderRoute: typeof ProjetosDashboardJuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificacoesRoute: CertificacoesRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosAnaliseVendasXsalesRoute: ProjetosAnaliseVendasXsalesRoute,
  ProjetosDashboardJuridicoRoute: ProjetosDashboardJuridicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
